### PR TITLE
Kong conf

### PR DESCRIPTION
**Pull request by akilleen**
Versions 0.9.0 and higher require serf to be installed and have changed the config file to .conf style. This PR allows this when you specify a version >= 0.9.0. This has only been tested against 0.10.3. 

If you have any suggestions on changes please let me know.

### CODE REVIEW

**Review by zuazo — CHANGES_REQUESTED** [review]
Wow! Amazing work :smiley:

Could you update the documentation in the README?

Also, the integration tests seem to be broken in Circle CI:

```
           * apt_package[curl for download_direct_from_oracle] action install[2017-10-25T21:00:04+00:00] INFO: Processing apt_package[curl for download_direct_from_oracle] action install (/tmp/kitchen/cache/cookbooks/java/providers/ark.rb line 73)
        (up to date)
           - download oracle tarball straight from the server[2017-10-25T21:00:06+00:00] FATAL: Failed to extract file jdk-7u75-linux-x64.tar.gz!
       
           ================================================================================
           Error executing action `install` on resource 'java_ark[jdk]'
           ================================================================================
           
           SystemExit
           ----------
           exit
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/java/providers/ark.rb:168:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/java/providers/ark.rb:145:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/java/recipes/oracle.rb
           
            61: java_ark 'jdk' do
            62:   url tarball_url
            63:   default node['java']['set_default']
            64:   checksum tarball_checksum
            65:   app_home java_home
            66:   bin_cmds bin_cmds
            67:   alternatives_priority node['java']['alternatives_priority']
            68:   retries node['java']['ark_retries']
            69:   retry_delay node['java']['ark_retry_delay']
            70:   connect_timeout node['java']['ark_timeout']
            71:   use_alt_suffix node['java']['use_alt_suffix']
            72:   reset_alternatives node['java']['reset_alternatives']
            73:   download_timeout node['java']['ark_download_timeout']
            74:   proxy node['java']['ark_proxy']
            75:   action :install
            76:   notifies :write, 'log[jdk-version-changed]', :immediately
            77: end
            78: 
            79: if node['java']['set_default'] && platform_family?('debian')
            80:   include_recipe 'java::default_java_symlink'
            81: end
            82: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/java/recipes/oracle.rb:61:in `from_file'
           
           java_ark("jdk") do
             action [:install]
             supports {:report=>true, :exception=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :java_ark
             cookbook_name "java"
             recipe_name "oracle"
             url "http://download.oracle.com/otn/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz"
             default true
             checksum "6f1f81030a34f7a9c987f8b68a24d139"
             app_home "/usr/lib/jvm/java-7-oracle-amd64"
             bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
             alternatives_priority 1062
             connect_timeout 600
             use_alt_suffix true
             reset_alternatives true
             download_timeout 600
             owner "root"
           end
           
           System Info:
           ------------
           chef_version=12.21.20
           platform=debian
           platform_version=7.11
           ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
           program_name=chef-client worker: ppid=95;start=20:59:49;
           executable=/opt/chef/bin/chef-client
           
       [2017-10-25T21:00:06+00:00] INFO: Running queued delayed notifications before re-raising exception
       
       Running handlers:
       [2017-10-25T21:00:06+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-10-25T21:00:06+00:00] ERROR: Exception handlers complete
       Chef Client failed. 10 resources updated in 16 seconds
       [2017-10-25T21:00:06+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-10-25T21:00:06+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-10-25T21:00:06+00:00] ERROR: java_ark[jdk] (java::oracle line 61) had an error: SystemExit: exit
       [2017-10-25T21:00:06+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
rake aborted!
Kitchen::InstanceFailure: Converge failed on instance <default-debian-7>.  Please see .kitchen/logs/default-debian-7.log for more details
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:86:in `call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:489:in `block in action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:488:in `action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:380:in `converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `each'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:157:in `verify'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:186:in `block in test'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:182:in `test'
/home/ubuntu/kong-cookbook/Rakefile:121:in `block in run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:121:in `run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:131:in `block (2 levels) in <top (required)>'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Kitchen::ActionFailed: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
CI="true"; export CI
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889 
']
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:86:in `call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:489:in `block in action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:488:in `action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:380:in `converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `each'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:157:in `verify'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:186:in `block in test'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:182:in `test'
/home/ubuntu/kong-cookbook/Rakefile:121:in `block in run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:121:in `run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:131:in `block (2 levels) in <top (required)>'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Kitchen::Transport::SshFailed: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
CI="true"; export CI
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889 
']
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/transport/ssh.rb:133:in `execute'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/transport/base.rb:120:in `execute_with_retry'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:75:in `block in call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/transport/ssh.rb:476:in `reuse_connection'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/transport/ssh.rb:88:in `connection'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/provisioner/base.rb:68:in `call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:489:in `block in action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:488:in `action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:380:in `converge_action'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `each'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:358:in `transition_to'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:157:in `verify'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:186:in `block in test'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.18.0/lib/kitchen/instance.rb:182:in `test'
/home/ubuntu/kong-cookbook/Rakefile:121:in `block in run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:121:in `run_kitchen'
/home/ubuntu/kong-cookbook/Rakefile:131:in `block (2 levels) in <top (required)>'
/home/ubuntu/kong-cookbook/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/bundle:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => integration => integration:docker
(See full trace by running task with --trace)
```

**Comment by akilleen** [comment]
I will take care of the README for sure.

However, I believe the integration tests seem to be broken in master. I get the same error when I pull from master and run the integration rake task.

**Comment by akilleen** [comment]
It appears that a java override fixes the issue. Not sure why to be honest, but noticed it worked in my wrapper cookbook because of java.

**Review by zuazo — CHANGES_REQUESTED** [review]
Thanks for your changes. So, we should update the version attribute, shouldn't we?

If you can also add the `serf` cookbook to the requirements list in the README. That would be fantastic.

Everything else is perfect!

**Comment by akilleen** [comment]
I have added serf to the requirements on the README. 

I see that the version is currently set to 0.6.0 in master, but the latest release is 0.5.0. Is 0.6.0 the version you want to release? Or do you want me to bump it to 0.6.1?

**Comment by akilleen** [comment]
I am also trying to fix the unit test coverage, but for the life of me cannot figure out why it's only picking on the remote_file for Ubuntu Precise. Maybe you can shed some light?

**Comment by zuazo** [comment]
Yeah, do not worry much about it. You have done more than enough :wink:

**Review by zuazo — APPROVED** [review]

**Pull request merged**
