### PR TITLE
quote yaml strings containing '.' or ':'

### PR DESCRIPTION
**Pull request by grimm26**
Fix for https://github.com/zuazo/kong-cookbook/issues/5:

> If I set something like cluster_listen or admin_api_listen in the kong.yml attributes, they get rendered by .to_yaml unquoted like so:
> 
> ``` yaml
> ---
> cluster_listen: 0.0.0.0:7946
> admin_api_listen: 0.0.0.0:8001
> ```
> 
> Kong wants those quoted:
> 
> ```
> $ sudo kong start
> [INFO] kong 0.8.2
> [INFO] Using configuration: /etc/kong/kong.yml
> [WARN] admin_api_listen: must be a string
> [WARN] cluster_listen: must be a string
> [ERR] Invalid properties in given configuration file
> ```

### CODE REVIEW

**Comment by zuazo** [comment]
Hi @grimm26, thanks for the report.

This seems a bug in Kong when parsing the YAML file, isn't it? I mean, the generated YAML is completely valid and those values should be read as strings.

**Comment by grimm26** [comment]
Yes, I did open https://github.com/Mashape/kong/issues/1277 with kong.  In the meantime, my patch let's the cookbook work until kong fixes upstream.

**Comment by grimm26** [comment]
Well, it looks like they marked my bug as Won't Fix because they are moving away from a yaml config file format.

**Comment by gravitystorm** [comment]
It would be great to fix this. Even if upstream are being daft about it (it's a bug, it should be fixed!), there's still plenty of people like me trying to use the kong cookbook with kong 0.8

I think it's fine to treat the kong.yml file as "something a bit like yaml but that needs special quoting" since that's how kong treats it when parsing it.

**Comment by zuazo** [comment]
Hi @grimm26,

Sorry for the delay in my response.

The problem I see with this PR is that I'm just not a fan of using `.gsub()` for that. Maybe traversing the hash an changing those specific values will be a better solution.

Aside from that, adding some unit or integration tests would be awesome.

**Comment by grimm26** [comment]
Kong no longer uses a yaml config so I was actually going to close this.

**Comment by zuazo** [comment]
@grimm26 As you prefer. I can undo the merge without problems.

What versions are affected by this problem?

Anyway. I'm going to try to update this cookbook to work for latest versions, so this change will probably disappear before the release.

**Comment by grimm26** [comment]
I'm using 0.9.x, which this cookbook doesn't handle so I wrote my own.  Postgresql database is now default.

**Comment by zuazo** [comment]
Released in [`0.5.0`](https://github.com/zuazo/kong-cookbook/releases/tag/0.5.0).

**Pull request merged**
